spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parkingLot
    username: postgres
    password: Raagu@20
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update # Ensures schema validation

#  flyway:
#    enabled: true
#    locations: classpath:db/migration

